#!/usr/bin/env bash

case "$1" in
    docker)
        echo "### building rawrepo-record-service docker ###"
        docker build . -t docker-io.dbc.dk/rawrepo-record-service:devel || exit 1
        if [[ ! -z "$BUILD_NUMBER" ]]; then
            docker tag docker-io.dbc.dk/rawrepo-record-service:devel docker-io.dbc.dk/rawrepo-record-service:${BRANCH_NAME}-${BUILD_NUMBER}
        fi
        ;;

    *)
        echo "### building rawrepo-record-service project ###"
        echo "### Look for build artifacts in target/ ###"

        mvn package -Dmaven.test.skip=true || exit 1
        ;;
esac